@startuml

together {
(Nais)
(Frontend)
(Pesys) as Pesys1
}

together {
(EUX)
(Joark)
(TPS)
(AktReg)
(Pesys) as Pesys2
}

package "App" {
Pesys1 --> [health]
Nais --> [health]
[security]
[metrics]
[utils]
[config]
}

package "Support API" as SupportAPI {
Frontend --> [arkivApi]
Frontend --> [personApi]
Frontend --> [pensjonApi]
Frontend --> [geoApi]
}

package "Fagmodul API" as FagmodulAPI {
Pesys1 --> [pensjonUtlandApi]
Frontend --> [bucSedApi]
}

package "EUXService" {
bucSedApi ---> [euxService]
euxService --> [euxBasisModel]
euxService --> [euxBucModel]
euxService ---> EUX
health ----> euxService
bucSedApi ---> euxBasisModel
bucSedApi ---> euxBucModel
}

bucSedApi --> [helper]
pensjonApi --> [helper]

package "Core" {
[models]
bucSedApi --> [prefill]
prefill -> [models]
prefill --> [sedModel]
}

bucSedApi -> models
pensjonUtlandApi --> models
euxService -> models
pensjonUtlandApi --> sedModel
bucSedApi --> sedModel
euxService --> sedModel

geoApi -> [geoService]
pensjonUtlandApi ---> [geoService]
prefill ---> [geoService]

arkivApi ---> [arkivService]
bucSedApi ---> [arkivService]
arkivService ---> Joark

together {
personApi ---> [aktoerregisterService]
aktoerregisterService --> AktReg
helper ---> [aktoerregisterService]
health ---> [personService]
personService -> TPS
personApi ---> [personService]
prefill ---> [personService]
}

health ---> [pensjonService]
pensjonApi ---> [pensjonService]
prefill ---> [pensjonService]
pensjonService -> Pesys2

App -[hidden]> SupportAPI
App -[hidden]> FagmodulAPI
@enduml
