kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-prefill-q2
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
    accessPolicy:
      outbound:
        rules:
          - application: eessi-pensjon-prefill-q2
            namespace: eessipensjon
            cluster: dev-gcp
      inbound:
        rules:
          - application: eessi-pensjon-fagmodul-q2
            namespace: eessipensjon
            cluster: dev-fss
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: PENSJONSINFORMASJON_URL
      value: https://pensjon-pen-q2.nais.preprod.local/pen/api/pensjonsinformasjon/v1
    - name: AZURE_APP_PEN_CLIENT_ID
      value: dev-fss.teampensjon.pensjon-pen-q2
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: AZURE_APP_PDL_CLIENT_ID
      value: dev-fss.pdl.pdl-api
    - name: OPENIDCONNECT_URL
      value: https://isso-q.adeo.no:443/isso
    - name: ONPREM_KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: KAFKA_STATISTIKK_TOPICNAME
      value: privat-eessipensjon-statistikk-q2
    - name: KAFKA_AUTOMATISERING_TOPIC
      value: eessipensjon.public-automatisering-q2
    - name: KODEVERK_REST_API_URL
      value: https://eessi-pensjon-onprem-proxy-q2.dev-fss-pub.nais.io
    - name: EESSI_PENSJON_INSTITUSJON
      value: NO:NAVAT07
    - name: EESSI_PENSJON_INSTITUSJON_NAVN
      value: NAV ACCEPTANCE TEST 07
    - name: ENV
      value: q2
  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-prefill-q2.internal.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 40
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 40
    failureThreshold: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: "4"
      memory: 8096Mi
    requests:
      cpu: 400m
      memory: 4024Mi
