kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-prefill-q1
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  kafka:
    pool: nav-dev
  envFrom:
    - secret: prefill-dev #secret name in Google Secret Manager
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: 6e921c7e-7b22-4c9a-9ff6-ee3719e3c4ba #Tilgang til 0000-ga-eessi-clerk-pensjon
          - id: 79c6b5b5-1144-495c-a2c9-78aebfb5faf4 #Tilgang til 0000-ga-eessi-clerk-ufore
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: eessi-pensjon-fagmodul-q1
          namespace: eessipensjon
          cluster: dev-gcp
    outbound:
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: kodeverk-api.nav.no
        - host: eessi-pensjon-fagmodul-q1.intern.dev.nav.no
        - host: eessi-pensjon-onprem-proxy-q1.intern.dev.nav.no
        - host: saf-q1.dev-fss-pub.nais.io
  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: PENSJONSINFORMASJON_URL
      value: https://eessi-pensjon-onprem-proxy-q1.dev-fss-pub.nais.io/pen/api/pensjonsinformasjon/v1
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: AZURE_APP_PDL_CLIENT_ID
      value: dev-fss.pdl.pdl-api
    - name: AZURE_APP_KODEVERK_CLIENT_ID
      value: kodeverk-api.nav.no
    - name: KAFKA_AUTOMATISERING_TOPIC
      value: eessipensjon.public-automatisering-q1
    - name: KODEVERK_URL
      value: https://kodeverk-api.nav.no
    - name: EESSI_PENSJON_INSTITUSJON
      value: NO:NAVAT07
    - name: EESSI_PENSJON_INSTITUSJON_NAVN
      value: NAV ACCEPTANCE TEST 07
    - name: AZURE_APP_PROXY_CLIENT_ID
      value: dev-fss.eessipensjon.eessi-pensjon-onprem-proxy-q2
    - name: AZURE_APP_SAF_CLIENT_ID
      value: dev-fss.teamdokumenthandtering.saf
    - name: ENV
      value: q1
  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-prefill-q1.intern.dev.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 40
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 40
    failureThreshold: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 60
  resources:
    limits:
      cpu: 4000m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 1Gi
