kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-prefill-q2
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  kafka:
    pool: nav-dev
  envFrom:
    - secret: prefill-dev #secret name in Google Secret Manager
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: eessi-pensjon-fagmodul-q2
          namespace: eessipensjon
          cluster: dev-gcp
  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: PENSJONSINFORMASJON_URL
      value: https://eessi-pensjon-onprem-proxy-q2.dev-fss-pub.nais.io/pen/api/pensjonsinformasjon/v1
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: AZURE_APP_PDL_CLIENT_ID
      value: dev-fss.pdl.pdl-api
    - name: AZURE_APP_KODEVERK_CLIENT_ID
      value: dev-fss.org.kodeverk
    - name: KAFKA_AUTOMATISERING_TOPIC
      value: eessipensjon.public-automatisering-q2
    - name: KODEVERK_URL
      value: https://kodeverk.dev-fss-pub.nais.io
    - name: EESSI_PEN_ONPREM_PROXY_URL
      value: https://eessi-pensjon-onprem-proxy-q2.dev-fss-pub.nais.io
    - name: EESSI_PENSJON_INSTITUSJON
      value: NO:NAVAT07
    - name: EESSI_PENSJON_INSTITUSJON_NAVN
      value: NAV ACCEPTANCE TEST 07
    - name: AZURE_APP_PROXY_CLIENT_ID
      value: dev-fss.eessipensjon.eessi-pensjon-onprem-proxy-q2
    - name: ENV
      value: q2
  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-prefill-q2.dev.intern.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 40
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 40
    failureThreshold: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 60
  resources:
    limits:
      cpu: "4"
      memory: "8192Mi"
    requests:
      cpu: "2"
      memory: "4096Mi"
