kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-prefill-q2
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  kafka:
    pool: nav-dev
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: PENSJONSINFORMASJON_URL
      value: https://pensjon-pen-q2.nais.preprod.local/pen/api/pensjonsinformasjon/v1
    - name: EESSIPEN_EUX_RINA_URL
      value: https://eux-rina-api-q2.nais.preprod.local/cpi
    - name: SAF_GRAPHQL_URL
      value: https://saf-q2.nais.preprod.local/graphql
    - name: SAF_HENTDOKUMENT_URL
      value: https://saf-q2.nais.preprod.local/rest/hentdokument
    - name: PDL_URL
      value: https://pdl-api.dev-fss.nais.io/graphql
    - name: OPENIDCONNECT_URL
      value: https://isso-q.adeo.no:443/isso
    - name: SECURITY_TOKEN_SERVICE_OPENID_CONFIGURATION_URL
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q2.preprod.local/SecurityTokenServiceProvider/
    - name: ONPREM_KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: KAFKA_STATISTIKK_TOPICNAME
      value: privat-eessipensjon-statistikk-q2
    - name: KAFKA_AUTOMATISERING_TOPIC
      value: eessipensjon.public-automatisering-q2
    - name: KODEVERK_REST_API_URL
      value: https://kodeverk.nais.adeo.no
    - name: EESSI_PENSJON_INSTITUSJON
      value: NO:NAVAT07
    - name: EESSI_PENSJON_INSTITUSJON_NAVN
      value: NAV ACCEPTANCE TEST 07
    - name: ENV
      value: q2
  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-prefill-q2.nais.preprod.local
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 40
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 40
    failureThreshold: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: "4"
      memory: 8096Mi
    requests:
      cpu: 400m
      memory: 4024Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{serviceuserkv}}
        mountPath: /var/run/secrets/nais.io/srveessipensjon
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/vault

