kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-prefill
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  envFrom:
    - secret: prefill #secret name in Google Secret Manager
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: 49d708e9-c141-4a01-9be9-aa539c48f1d2 #Tilgang til 0000-ga-eessi-clerk-pensjon
          - id: fedabd32-4cab-4307-ad69-ea24edc69790 #Tilgang til 0000-ga-eessi-clerk-ufore
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: eessi-pensjon-fagmodul
          namespace: eessipensjon
          cluster: prod-gcp
        - application: etterlatte-api
          namespace: etterlatte
          cluster: prod-gcp
    outbound:
      rules:
        - application: etterlatte-api
          namespace: etterlatte
          cluster: prod-gcp
      external:
        - host: pdl-api.prod-fss-pub.nais.io
        - host: kodeverk-api.nav.no
        - host: eessi-pensjon-fagmodul.intern.nav.no
        - host: digdir-krr-proxy.intern.nav.no
        - host: pensjon-pen.prod-fss-pub.nais.io
  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod

    - name: PENSJONSINFORMASJON_URL
      value: https://pensjon-pen.prod-fss-pub.nais.io/pen/api/pensjonsinformasjon/v1
    - name: AZURE_APP_PEN_CLIENT_ID
      value: prod-fss.pensjondeployer.pensjon-pen

    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: AZURE_APP_PDL_CLIENT_ID
      value: prod-fss.pdl.pdl-api

    - name: KRR_URL
      value: https://digdir-krr-proxy.intern.nav.no
    - name: KRR_CLIENT_ID
      value: prod-gcp.team-rocket.digdir-krr-proxy

    - name: KODEVERK_URL
      value: https://kodeverk-api.nav.no
    - name: AZURE_APP_KODEVERK_CLIENT_ID
      value: prod-gcp.team-rocket.kodeverk-api

    - name: ETTERLATTE_URL
      value: http://etterlatte-api.etterlatte
    - name: AZURE_APP_ETTERLATTE_CLIENT_ID
      value: prod-gcp.etterlatte.etterlatte-api

    - name: KAFKA_AUTOMATISERING_TOPIC
      value: eessipensjon.public-automatisering

    - name: EESSI_PENSJON_INSTITUSJON
      value: NO:889640782
    - name: EESSI_PENSJON_INSTITUSJON_NAVN
      value: "The Norwegian Labour and Welfare Administration"

    - name: ENV
      value: p

  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-prefill.intern.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 40
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 40
    failureThreshold: 10
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: 4000m
      memory: 1Gi
    requests:
      cpu: 600m
      memory: 1Gi
